# Generated by Django 3.1.7 on 2021-05-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('prediction', models.TextField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
